[package]
name = "server"
version = "0.2.0"
authors = [
    "gbenattar <g.benattar@gmail.com>",
    "Oded Leiba <odedleiba5@gmail.com"
]
edition = "2018"

[lib]
name = "server_lib"
path = "src/lib.rs"

[[bin]]
name = "server_exec"
path = "src/main.rs"

[dependencies.shared]
path = "../shared"

[dependencies]
rocket = { version = "0.4.2", default-features = false }
rocket_contrib = { version = "0.4.2", default-features = false,features = ["json"] }
rocksdb = "0.10.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rusoto_dynamodb = "0.36.0"
rusoto_core = "0.36.0"
time-test = "0.2.1"
log = "0.4"
config = "0.9.2"
uuid = { version = "0.7", features = ["v4"] }
error-chain = "0.12.0"
failure = "0.1.5"
jsonwebtoken = "6.0.1"
rust-crypto = "0.2"
hex = "0.3.2"
floating-duration = "0.1.2"
bitcoin = { version = "0.20", features = [ "use-serde" ] }
rand = "0.6.5"
ecies = "0.1.4"
libsecp256k1 = "0.3.5"

[dependencies.zk-paillier]
git = "https://github.com/KZen-networks/zk-paillier"
tag = "v0.2.4"

[dependencies.kms]
git = "https://github.com/KZen-networks/kms-secp256k1"
tag = "v0.2.0"

[dependencies.multi-party-ecdsa]
git = "https://github.com/KZen-networks/multi-party-ecdsa"
tag = "v0.2.5"

[dependencies.multi-party-eddsa]
git = "https://github.com/KZen-networks/multi-party-eddsa"
tag = "v0.2.1"

[dependencies.multi-party-schnorr]
git = "https://github.com/KZen-networks/multi-party-schnorr"
tag = "v0.3.1"

[dependencies.curv]
git = "https://github.com/KZen-networks/curv"
tag = "v0.2.2"
features =  ["ec_secp256k1"]

[dependencies.serde_dynamodb]
git = "https://github.com/KZen-networks/serde_dynamodb"

[patch.crates-io]
rust-gmp = { version = "0.5.0", features = ["serde_support"], git = "https://github.com/KZen-networks/rust-gmp" }

